---
title: "Transformations"
output: html_notebook
---


```{r}
library(astsa)
library(xts)
library(tsbox)
library(MASS)
```

```{r}
setwd('~/Documents/projects/MATH598_Final/notebooks/Monthly')

source('MonthlyConvert.R')
```

```{r}
data = ts(data,freq=12
          )

```

```{r}
model = lm(data ~ time(data) + factor(cycle(data)))
modelfit = ts(fitted(model),start=start(data),frequency=frequency(data))

plot(data)
lines(modelfit,col=2,lty=2)
plot(model$residuals,type='l')
```

```{r}
candmod = arima(data, order=c(1,0,0), include.mean
= FALSE,method='ML')

plot(candmod$residuals)
acf(candmod$residuals,na.action = na.pass)
pacf(candmod$residuals,na.action = na.pass)
```

```{r}
time2 = time(data)^2
quadmodel = lm(data ~ time2 + time(data) + factor(cycle(data)))
quadmodelfit = ts(fitted(quadmodel),start=start(data),frequency=frequency(data))

plot(data)
lines(quadmodelfit,col=2,lty=2)
plot(quadmodel$residuals,type='l')
```
```{r}

simpmodel = lm(data ~ + factor(cycle(data)))
simpmodelfit = ts(fitted(simpmodel),start=start(data),frequency=frequency(data))

plot(data)
lines(simpmodelfit,col=2,lty=2)
plot(simpmodel$residuals,type='l')
```

s

```{r}
detrended = model$residuals

```

Conclusions:
1) 5 year data does not seem to be a long enough look to accurately establish an overall trend
2) When 10 year trend is looked at, linear and quad fits are nearly identical.
3) Transforming the data with candidate transformations did not seem to produce any meaningful results

